
version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend

  mongodb:
    restart: always
    image: mongo
    ports:
      - "27017:27017"

  api:
    restart: always
    build:
      context: api
    image: inventory-api
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test 
    ports:
      - "5000:5000"
    
  frontend:
    restart: always
    build:
      context: frontend
    image: inventory-frontend
    ports:
      - "3000:3000"
volumes:
  jenkins_home:
